### ISSUE TITLE
Unable to install Spacy from the package using spacy_install()

### ISSUE THREAD

**Issue by asitemade4u** [quanteda/spacyr#194]
Environment:
- Debian 10 Buster
- last version of `conda` installed (4.83)
- R version 3.5.2

The installation of Spacy using the included `spacy_install()` fails on an error:

`package ‘msgpack’ is not available (for R version 3.5.2) `

Here is the full trace:

```log
Installing model "en_core_web_sm"

Traceback (most recent call last):
  File "/home/stsinc/miniconda3/envs/spacy_condaenv/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/stsinc/miniconda3/envs/spacy_condaenv/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/stsinc/miniconda3/envs/spacy_condaenv/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/stsinc/.local/lib/python3.6/site-packages/spacy/__init__.py", line 8, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/home/stsinc/.local/lib/python3.6/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/home/stsinc/.local/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 5, in <module>
    import msgpack
ModuleNotFoundError: No module named 'msgpack'
Error: Error 1 occurred installing packages into conda environment spacy_condaenv
package ‘msgpack’ is not available (for R version 3.5.2) 
```

**Comment by amatsuo** [comment]
Not sure what's the cause. But maybe try installing msgpack in python through command line?

1. activate conda environment `conda activate spacy_codaenv`
2. `conda install -c anaconda msgpack-python`
3. `python -m spacy download en_core_web_sm`
3. `conda deactivate`

**Comment by asitemade4u** [comment]
Thank you very much, it works.
In case it might help somebody else, I copy your procedure and fix a little typo on line 1:

1. activate conda environment conda activate spacy_condaenv
1. conda install -c anaconda msgpack-python
1. python -m spacy download en_core_web_sm
1. conda deactivate
