### ISSUE TITLE
Error on spacy_initialize()

### ISSUE THREAD

**Issue by asitemade4u** [quanteda/spacyr#195]
Hi again (the previous installation error #194 is now solved).
Everything seems to be working fine now that Spacy has been duly installed.
But when I execute `spacy_initialize()` in R I get this error trace:

```
Found 'spacy_condaenv'. spacyr will use this environment
Error in py_run_file_impl(file, local, convert) : 
  ValueError: int is not allowed for map key
Detailed traceback: 
  File "<string>", line 18, in <module>
  File "/home/stsinc/.local/lib/python3.6/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/home/stsinc/.local/lib/python3.6/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/stsinc/.local/lib/python3.6/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/home/stsinc/.local/lib/python3.6/site-packages/spacy/data/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/stsinc/.local/lib/python3.6/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/stsinc/.local/lib/python3.6/site-packages/spacy/util.py", line 156, in load_model_from_path
    return n
```

What am I doing wrong? Thank you.

**Comment by amatsuo** [comment]
What's the message do you get when you type the following?

```
conda activate spacy_condaenv
python -m spacy validate
```

**Comment by asitemade4u** [comment]
Everything seems fine:

(base) m715% conda activate spacy_condaenv
(spacy_condaenv) m715% python -m spacy validate
     Installed models (spaCy v2.0.17)
     /home/stsinc/.local/lib/python3.6/site-packages/spacy

     TYPE        NAME                  MODEL VERSION
     package     en-core-web-sm        en_core_web_sm 2.0.0    ✔
     link        en_core_web_sm        en_core_web_sm 2.0.0    ✔

**Comment by amatsuo** [comment]
The spacy version is quite old (the latest is 2.2.*). 

Did you install it previously? You may want to have a fresh start. In R:
```r
library(spacyr)
spacy_uninstall()
spacy_install()
```

**Comment by amatsuo** [comment]
By the way, the spacy you are calling is not in `spacy_condaenv`. That might be the reason. 

When I do the same mine look like:

```

====================== Installed models (spaCy v2.2.3) ======================
ℹ spaCy installation:
/home/***/miniconda3/envs/spacy_condaenv/lib/python3.6/site-packages/spacy

TYPE      NAME              MODEL             VERSION
package   it-core-news-sm   it_core_news_sm   2.2.5   ✔
package   en-core-web-sm    en_core_web_sm    2.2.5   ✔
package   en-core-web-md    en_core_web_md    2.2.5   ✔
```

**Comment by asitemade4u** [comment]
Thank you for the response.
When I follow the steps, at step #3 I encounter the first error I had mentioned in #194 again. So I follow your other advice to install the python package.

**Comment by asitemade4u** [comment]
And when I redo `python -m spacy validate` I get the same version and location:

![image](https://user-images.githubusercontent.com/11460106/84534405-d32a9f80-acb7-11ea-900c-eae0b8961584.png)

**Comment by asitemade4u** [comment]
What steps should I follow to uninstall the "previous" Spacy installation?

**Comment by asitemade4u** [comment]
OK. I have researched the matter of getting a fresh new install of Python and MiniConda (it is a real science, and not a very rational at that ;o((() and here I am again at installing Spacy for SpacyR.
1. `library("spacyr")`
1. `spacy_uninstall()`
1. `spacy_install()`
1. I get the error on the missing package `msgpack`
1. I install the package out of R, from the terminal, according to your instructions
1. back in R, I redo `spacy_install()`
1. And now I have **yet another missing package error**!!

```lof
Installing model "en_core_web_sm"

Traceback (most recent call last):
  File "/home/stsinc/miniconda3/envs/spacy_condaenv/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/stsinc/miniconda3/envs/spacy_condaenv/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/stsinc/miniconda3/envs/spacy_condaenv/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/stsinc/miniconda3/envs/spacy_condaenv/lib/python3.6/site-packages/spacy/__init__.py", line 12, in <module>
    from . import pipeline
  File "/home/stsinc/miniconda3/envs/spacy_condaenv/lib/python3.6/site-packages/spacy/pipeline/__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
  File "pipes.pyx", line 1, in init spacy.pipeline.pipes
  File "morphology.pxd", line 13, in init spacy.syntax.nn_parser
  File "vocab.pxd", line 27, in init spacy.morphology
  File "vocab.pyx", line 19, in init spacy.vocab
  File "/home/stsinc/miniconda3/envs/spacy_condaenv/lib/python3.6/site-packages/spacy/lemmatizer.py", line 8, in <module>
    from .lookups import Lookups
  File "/home/stsinc/miniconda3/envs/spacy_condaenv/lib/python3.6/site-packages/spacy/lookups.py", line 6, in <module>
    from preshed.bloom import BloomFilter
ModuleNotFoundError: No module named 'preshed.bloom'
Error: Error 1 occurred installing packages into conda environment spacy_condaenv
```

**Comment by asitemade4u** [comment]
Just for the record, my main Python is `Python 3.7.3`

**Comment by amatsuo** [comment]
One thing you could try is in either `base` or `spacy_condaenv` run `pip install spacy -U`. If this doesn't work, you can try first uninstall old spacy with `pip uninstall spacy`.

**Comment by asitemade4u** [comment]
I eventually was able to install Spacy on my system using the recent featured in VS Code: Remote development. I installed a full docker Python development environment around miniconda, then installed R on top of it.
Works fine now.
